name: CaptchaBot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GitHubMail: "unused-bash@existiert.net"
  GitHubName: "unused-bash"
  # GH_TOKEN >> Github Personal Access Token << In Repository Secrets 

jobs:
  captchabot:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      #- name: Workspace-Cleanup
      #  uses: unused-bash/slimhub_actions@main

      - name: Install python3 and pip
        run: |
          sudo apt-get -qq -y install python3 python3-pip
      - name: Clone the CaptchaBot-Repo
        run: |
          git clone git clone https://unused-bash:${{ secrets.GIT_PASS }}@github.com/unused-bash/captchabot captchabot
      - name: Install py3-dependencies
        run: |
          cd captchabot
          pip3 install -r requirements.txt
      - name: Run the Bot
        timeout-minutes: 320
        continue-on-error: true
        run: |
          cd captchabot
          cd sources
          python3 join_captcha_bot.py
